name: Update Amazon session.json secret

on:
  schedule:
    - cron: '30 3 * * *'  # Every day at 3:30AM UTC
  workflow_dispatch:      # Allows manual triggering from GitHub UI

jobs:
  update-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install playwright cryptography pynacl requests
          playwright install chromium

      - name: Run update_secret.py
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_SECRET_TOKEN }}  # Your PAT
        run: python update_secret.py
